CodingContainer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path
from user import views


# TEMPLATE TAGGING
app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('containers', views.containers, name='containers'),
    path('images', views.images, name='images'),
    path('create', views.create_container, name='create_container'),
    path('getContainers', views.get_containers, name='get_containers'),
    path('deleteContainer', views.remove_container, name='remove_container'),
    path('openport', views.open_port, name='openPort'),
    path('initial_setup', views.initial_setup, name='initial_setup'),
    path('profile', views.profile, name='profile'),
    path('change_password', views.change_password, name='change_password'),
    path('files', views.files, name='files'),
    path('editor', views.editor, name='editor'),
    path('directory', views.get_directory, name='directory'),
    path('edit_file', views.edit_file, name='edit_file'),
]

user/models.py
from django.db import models

# Create your models here.


class UserProfile(models.Model):

    username = models.CharField(max_length=256)
    password = models.CharField(max_length=256)
    enrollment_id = models.IntegerField(unique=True, primary_key=True)
    email = models.CharField(unique=True, max_length=256)

    def __str__(self):
        return str(self.enrollment_id)

user/forms.py
from django import forms
from user.models import UserProfile


class UserForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('username', 'password', 'email', 'enrollment_id')

user/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls.base import reverse
from django.shortcuts import render
from django.contrib import messages
from user.forms import UserForm
from user.models import UserProfile
import requests
import json


base_url = "http://spr.openport.io:11264"
token = "Token 4147d4512235bf845a7e8111a6c934cc5c416024"
# base_url = "http://localhost:8000"


def initial_setup(request):
    url = "https://spr.openport.io/l/11264/Zy1VU4Aqax7bWMMT"
    payload = ""
    headers = {
        'cache-control': "no-cache",
        'Postman-Token': "a1ec5098-d35b-4422-ba8b-e84baf36fe6c"
    }
    response = requests.request("GET", url, data=payload, headers=headers)
    return HttpResponseRedirect(reverse('user:index'))


def index(request):
    if request.method == "POST":
        print(request.POST)
    message = None
    for msg in messages.get_messages(request):
        message = msg
        break

    if 'enrollment_id' in request.session:
        return render(request, 'user/index.html', {'loggedIn': True, 'message': message})

    return render(request, 'user/index.html', {'message': message})


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.password = make_password(request.POST.get('password'))
            user.save()

            url = base_url + "/api/v2/users/"
            payload = json.dumps({"user_id": request.POST.get('enrollment_id')})
            headers = {
                'Authorization': token,
                'Content-Type': "application/json",
                'cache-control': "no-cache",
            }

            response = requests.request("POST", url, data=payload, headers=headers)
            print(response.status_code)
            print(response.text)

            registered = True
            messages.add_message(request, messages.INFO, 'Registration completed. Login to continue...')
            return HttpResponseRedirect(reverse('user:login'))

        else:
            print(user_form.errors)
            message = None
            if 'Enrollment' in str(user_form.errors):
                message = 'User already exists with this Enrollment Id'
            else:
                message = 'User already exists with this Email'
            if 'Enrollment' in str(user_form.errors) and 'Email' in str(user_form.errors):
                message = 'User already exists with this Enrollment Id and Email'

            messages.add_message(request, messages.INFO, message)
            return HttpResponseRedirect(reverse('user:register'))

    if 'enrollment_id' in request.session:
        return HttpResponseRedirect(reverse('user:index'))

    message = None
    for msg in messages.get_messages(request):
        message = msg
        break

    return render(request, 'user/register.html', {'registered': registered, 'message': message})


def login(request):
    if request.method == "POST":
        enrollment_id = int(request.POST.get('enrollment_id'))
        password = request.POST.get('password')

        if enrollment_id in list(UserProfile.objects.values_list('pk', flat=True)):
            user = UserProfile.objects.get(enrollment_id=enrollment_id)

            if check_password(password, user.password):
                request.session['enrollment_id'] = user.enrollment_id
                request.session['username'] = user.username
                request.session['email'] = user.email
                messages.add_message(request, messages.INFO, 'Logged In Successfully')
                return HttpResponseRedirect(reverse('user:dashboard'))
            else:
                messages.add_message(request, messages.INFO, 'Invalid Credentials')
                return HttpResponseRedirect(reverse('user:login'))

        else:
            messages.add_message(request, messages.INFO, 'User Does Not Exists')
            return HttpResponseRedirect(reverse('user:login'))

    if 'enrollment_id' in request.session:
        return HttpResponseRedirect(reverse('user:index'))

    message = None
    for msg in messages.get_messages(request):
        message = msg
        break

    return render(request, 'user/login.html', {'message': message})


def logout(request):
    try:
        del request.session['enrollment_id']
        del request.session['username']
        del request.session['mail']
    except KeyError as err:
        print(err)

    messages.add_message(request, messages.INFO, 'Logged Out Successfully')
    return HttpResponseRedirect(reverse('user:index'))


def dashboard(request):
    return HttpResponseRedirect(reverse('user:containers'))
    # message = None
    # for msg in messages.get_messages(request):
    #     message = msg
    #     break
    #
    # if 'enrollment_id' in request.session:
    #     return render(request, 'user/dashboard.html', {'loggedIn': True, 'message': message})
    #
    # return render(request, 'user/dashboard.html', {})


def containers(request):
    message = None
    for msg in messages.get_messages(request):
        message = msg
        break

    if 'enrollment_id' not in request.session:
        messages.add_message(request, messages.INFO, 'You are not logged in..!')
        return HttpResponseRedirect(reverse('user:index'))

    return render(request, 'user/containers.html')


def profile(request):
    if 'enrollment_id' not in request.session:
        return HttpResponseRedirect(reverse('user:index'))

    return render(request, 'user/profile.html')


def images(request):
    url = base_url + "/api/v2/images/"

    headers = {
    'Authorization': token,
    'Content-Type': "application/json",
    'cache-control': "no-cache",
    }

    response = requests.request("GET", url, headers=headers)
    print(response.status_code)
    print(response.text)
    if response.status_code == 200:
        images = dict()
        data = json.loads(response.text)
        for i in range(len(data)):
            images[i] = data[i]['name']

        return JsonResponse(images)

    return JsonResponse("Something went wrong!")


def create_container(request):
    if request.method == "POST":
        url = base_url + "/api/v2/containers/"
        print(request.POST)
        payload = json.dumps({
            "user_id": request.POST.get('user_id'),
            "image": request.POST.get('image'),
            "name": request.POST.get('name').lower()
        })
        headers = {
            'Authorization': token,
            'Content-Type': "application/json",
            'cache-control': "no-cache",
        }

        response = requests.request("POST", url, data=payload, headers=headers)
        print(response.status_code)
        # print(response.text)
        data = json.loads(response.text)
        data['local_ports'] = json.loads(data['local_ports'])
        return JsonResponse(data)

    return JsonResponse({})


def get_containers(request):

    url = base_url + "/api/v2/users/" + str(request.session['enrollment_id'])
    headers = {
        'Authorization': token,
        'cache-control': "no-cache",
    }
    response = requests.request("GET", url, headers=headers)
    # print(response.text)
    print(response.status_code)

    containers_data = (json.loads(response.text))['containers']
    data = dict()
    for i in range(len(containers_data)):
        containers_data[i]['local_ports'] = json.loads(containers_data[i]['local_ports'])
        if containers_data[i]['external_ports'] != '':
            containers_data[i]['external_ports'] = json.loads(containers_data[i]['external_ports'])
        data[i] = containers_data[i]
        # print(containers_data[i])

    return JsonResponse(data)


def remove_container(request):
    if request.method == "GET":
        url = base_url + "/api/v2/containers/" + request.GET.get('container_id') + "/"
        headers = {
            'Authorization': token,
            'cache-control': "no-cache",
        }

        response = requests.request("DELETE", url, headers=headers)
        print(response.text)

        return JsonResponse({'result': "Deleted Successfully"})

    return JsonResponse({'result': "Some Error occurred"})


def open_port(request):
    if request.method == "GET":
        container_id = str(request.GET.get('container_id'))
        port = str(request.GET.get('port'))

        url = base_url + "/api/v2/openport/" + container_id + '/' + port
        payload = json.dumps({})

        headers = {
            'Authorization': token,
            'Content-Type': "application/json",
            'cache-control': "no-cache",
        }

        response = requests.request("GET", url, data=payload, headers=headers)
        print(json.loads(response.text))

        return JsonResponse({'ip': json.loads(response.text)[port]})

    return JsonResponse({'result': 'Some error occurred'})


def change_password(request):
    changed = False
    enrollment_id = int(request.POST.get('enrollment_id'))
    current_password = request.POST.get('current_password')
    new_password = request.POST.get('new_password')

    if request.method == "POST":
        user = UserProfile.objects.get(enrollment_id=enrollment_id)

        if not check_password(current_password, user.password):
            return JsonResponse({'changed': changed, 'current_password': 'wrong'})
        else:
            user.password = make_password(new_password)
            user.save()
            changed = True
            return JsonResponse({'changed': changed, 'current_password': 'matched'})

    return JsonResponse({'changed': changed, 'current_password': 'wrong'})


def files(request):
    if 'enrollment_id' not in request.session:
        return HttpResponseRedirect(reverse('user:index'))

    return render(request, 'user/files.html')

templates/user/home_base.html
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head %}{% endblock %}

    <!-- Favicon -->
    <link href="{% static 'dashboard/assets/img/brand/favicon.png' %}" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="{% static 'dashboard/assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="{% static 'dashboard/assets/css/argon.css' %}?v=1.0.0" rel="stylesheet">
</head>

<body>

{% block body %}{% endblock %}

<!-- Argon Scripts -->
<!-- Core -->
<script src="{% static 'dashboard/assets/vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- Optional JS -->
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
<!-- Argon JS -->
<script src="{% static 'dashboard/assets/js/argon.js' %}?v=1.0.0"></script>

{% block script %}{% endblock %}

</body>
</html>

templates/user/index.html
<!DOCTYPE html>
{% extends 'user/login_base.html' %}

{% load staticfiles %}

{% block head %}
    <title>Coding Container - A Web App For Private Virtual Server</title>
{% endblock %}

{% block body %}
    <header class="header-global">
        <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
            <div class="container">
                <a class="navbar-brand pt-0" style="font-size: 1.25rem" href="{% url 'user:index' %}">
                    <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                    <span class="btn-inner--text text-blue">Coding Container</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbar_global">
                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a class="pt-0" style="font-size: 1.25rem" href="{% url 'user:index' %}">
                                    <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                                    <span class="btn-inner--text text-blue">Coding Container</span>
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                                    <span></span>
                                    <span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <ul class="navbar-nav align-items-lg-center ml-lg-auto">
                        {% if loggedIn %}
                            <li class="nav-item nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'user:dashboard' %}" class="btn btn-outline-neutral">
                                    <span class="nav-link-inner--text">Dashboard</span>
                                </a>
                            </li>
                            <li class="nav-item nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'user:logout' %}" class="btn btn-neutral">
                                    <span class="nav-link-inner--text">Log out</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item  nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'user:login' %}" class="btn btn-outline-neutral">
                                    <span class="nav-link-inner--text">Sign in</span>
                                </a>
                            </li>
                            <li class="nav-item nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'user:register' %}" class="btn btn-neutral">
                                    <span class="nav-link-inner--text">Sign up</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="position-relative">
            <!-- shape Hero -->
            <section class="section section-lg section-shaped pb-250">
                <div class="shape shape-style-1 shape-default">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                {% if message %}
                    <p class="lead text-center text-white">{{ message }}</p>
                {% endif %}
                <div class="container py-lg-md d-flex">
                    <div class="col px-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <h1 class="display-3  text-white">Ready to start coding with Coding Container?
                                    <span>with pre-built coding environment</span>
                                </h1>
{#                                <p class="lead  text-white">The design system comes with four pre-built pages to help you#}
{#                                    get started faster. You can change the text and images and you're good to go.</p>#}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- SVG separator -->
                <div class="separator separator-bottom separator-skew">
                    <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1"
                         xmlns="http://www.w3.org/2000/svg">
                        <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
                    </svg>
                </div>
            </section>
            <!-- 1st Hero Variation -->
        </div>
        <section class="section section-lg pt-lg-0 mt--200">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="row row-grid">
                            <div class="col-lg-4">
                                <div class="card card-lift--hover shadow border-0">
                                    <div class="card-body py-5">
                                        <div class="icon icon-shape icon-shape-primary rounded-circle mb-4">
                                            <i class="fa fa-edit"></i>
                                        </div>
                                        <h6 class="text-primary text-uppercase">Editor</h6>
                                        <p class="description mt-3">With the amazing editor in Codeanywhere,
                                            you will forget you ever used any other code editor.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card card-lift--hover shadow border-0">
                                    <div class="card-body py-5">
                                        <div class="icon icon-shape icon-shape-success rounded-circle mb-4">
                                            <i class="ni ni-controller"></i>
                                        </div>
                                        <h6 class="text-success text-uppercase">Remote Connection</h6>
                                        <p class="description mt-3">Edit your code remotely wherever it is; FTP, SFTP,
                                            even Dropbox or Google Drive and more.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card card-lift--hover shadow border-0">
                                    <div class="card-body py-5">
                                        <div class="icon icon-shape icon-shape-warning rounded-circle mb-4">
                                            <i class="fa fa-terminal"></i>
                                        </div>
                                        <h6 class="text-warning text-uppercase">Terminal console</h6>
                                        <p class="description mt-3">Use built-in terminal console to run any command on
                                            your Container or even remote servers (using SSH).</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

templates/user/login.html
<!DOCTYPE html>
{% extends 'user/login_base.html' %}

{% load staticfiles %}

{% block head %}
    <title>Login</title>
{% endblock %}

{% block body %}

<header class="header-global">
    <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
        <div class="container">
            <a class="navbar-brand pt-0" style="font-size: 1.25rem" href="{% url 'user:index' %}">
                <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                <span class="btn-inner--text text-blue">Coding Container</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global"
                    aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbar_global">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a class="pt-0" style="font-size: 1.25rem" href="{% url 'user:index' %}">
                                <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                                <span class="btn-inner--text text-blue">Coding Container</span>
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse"
                                    data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false"
                                    aria-label="Toggle navigation">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<main>
    <section class="section section-shaped section-lg">
        <div class="shape shape-style-1 bg-gradient-default">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
        {% if message %}
        <p class="lead text-center text-white">{{ message }}</p>
        {% endif %}
        <div class="container pt-lg-md">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card bg-secondary shadow border-0">
                        <div class="card-body px-lg-5 py-lg-5">
                            <div class="text-center display-4 mb-4">
                                <large>Sign In With Credentials</large>
                            </div>
                            <form role="form" method="post">
                                <div class="form-group">
                                    <div class="input-group input-group-alternative mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                        </div>
                                        <input class="form-control" placeholder="Enrollment ID" type="number" name="enrollment_id" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                        </div>
                                        <input class="form-control" placeholder="Password" type="password" name="password" required>
                                    </div>
                                </div>
{#                                <div class="custom-control custom-control-alternative custom-checkbox">#}
{#                                    <input class="custom-control-input" id=" customCheckLogin" type="checkbox">#}
{#                                    <label class="custom-control-label" for=" customCheckLogin">#}
{#                                        <span>Remember me</span>#}
{#                                    </label>#}
{#                                </div>#}
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary my-4">Sign in</button>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-6">
                            <a href="#" class="text-light">
                                <small>Forgot password?</small>
                            </a>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{% url 'user:register' %}" class="text-light">
                                <small>Create new account</small>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

templates/user/login_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head %}{% endblock %}

    <!-- Favicon -->
    <link href="{% static 'login/img/brand/favicon.png' %}" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="{% static 'login/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
    <link href="{% static 'login/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="{% static 'login/css/argon.css' %}?v=1.0.1" rel="stylesheet">
    <!-- Docs CSS -->
    <link type="text/css" href="{% static 'login/css/docs.min.css' %}" rel="stylesheet">
</head>

<body>

{% block body %}{% endblock %}

{#<footer class="footer has-cards">#}
{#    <div class="container">#}
{#        <hr>#}
{#        <div class="row align-items-center justify-content-md-between">#}
{#            <div class="col-md-6">#}
{#                <div class="copyright">#}
{#                    &copy; 2019#}
{#                    <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-6">#}
{#                <ul class="nav nav-footer justify-content-end">#}
{#                    <li class="nav-item">#}
{#                        <a href="" class="nav-link" target="_blank">Creative Tim</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a href="" class="nav-link" target="_blank">About Us</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a href="" class="nav-link" target="_blank">Blog</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a href="" class="nav-link" target="_blank">MIT License</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</footer>#}
<!-- Core -->
<script src="{%  static 'login/vendor/jquery/jquery.min.js' %}"></script>
<script src="{%  static 'login/vendor/popper/popper.min.js' %}"></script>
<script src="{%  static 'login/vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'login/vendor/headroom/headroom.min.js' %}"></script>
<!-- Argon JS -->
<script src="{% static 'login/js/argon.js' %}"></script>

{% block scripts %}{% endblock %}

</body>

</html>